### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by cawetzel** [Martinzm1/Embedded-2-Project#6]
`Server`
LED
Filter buffer values
Send filtered data
transient region
Save data to file
Handle ch0 low
Send Finished signal

`Client`
Handle name prefix
MATLAB to determine if getting correct values

**Comment by Martinzm1** [comment]
>Client
Can now handle prefix
MATLAB convolution function gives same values as client.
Needs to fix transient region.(either in client or in server)

>Server
dtcopy works with upto date client
can handle filter coefficients
can write unfiltered data to file

**Comment by cawetzel** [comment]
Fix Transient Region
Area under curve
malloc on client
